import { z } from 'zod';

export const articleSchema = z.object({
  slug: z.string(),
  contentType: z.enum(['editorial', 'briefing']),
  sourceName: z.string().nullable().optional(),
  originalUrl: z.string().url().nullable().optional(),
  title: z.string(),
  author: z.string(),
  publishDate: z.union([z.date(), z.string().pipe(z.coerce.date())]),
  issueNo: z.number().optional(),
  volumeNo: z.number().optional(),
  tags: z.array(z.string()).optional(),
  imageUrl: z.string().nullable().optional(),
  hub: z.string().nullable().optional(),
  excerpt: z.string().nullable().optional(),
  author_take_question1: z.string().nullable().optional(),
  author_take_answer1: z.string().nullable().optional(),
  author_take_question2: z.string().nullable().optional(),
  author_take_answer2: z.string().nullable().optional(),
  contentBody: z.string().nullable().optional(),
});

export const jobSchema = z.object({
  id: z.string(),
  title: z.string(),
  company: z.string(),
  location: z.string(),
  applicationLink: z.string().url(),
  postedDate: z.union([z.date(), z.string().pipe(z.coerce.date())]),
  expirationDate: z.union([z.date(), z.string().pipe(z.coerce.date())]).nullable().optional(),
  tags: z.array(z.string()).optional(),
  status: z.enum(['draft', 'pending_review', 'pending_approval', 'published', 'rejected']),
  jobLevel: z.string().nullable().optional(),
  employeeRole: z.string().nullable().optional(),
  salaryRange: z.string().nullable().optional(),
  hasSalary: z.boolean().optional(),
  source: z.string().nullable().optional(),
  sourceUrl: z.string().url().nullable().optional(),
  verificationDate: z.union([z.date(), z.string().pipe(z.coerce.date())]).nullable().optional(),
  glassdoorLink: z.string().url().nullable().optional(),
  crunchbaseLink: z.string().url().nullable().optional(),
  companyLogoUrl: z.string().nullable().optional(),
  applicationExperience: z.string().optional(),
  excerpt: z.string(),
  description: z.string().optional(),
  responsibilities: z.array(z.string()).optional(),
  qualifications: z.array(z.string()).optional(),
  story_question1: z.string().optional(),
  story_answer1: z.string().optional(),
  story_question2: z.string().optional(),
  story_answer2: z.string().optional(),
  story_question3: z.string().optional(),
  story_answer3: z.string().optional(),
  companyCulture: z.string().optional(),
  tweetableDescription: z.string().optional(),
});
